import { ESHOP_DEPARTMENTS } from "@/data/eshop-catalog";

/**
 * Synonyms, spacing variants, and extra catalog lines for crawlable / structured-data coverage.
 * Merged with `ESHOP_DEPARTMENTS` lines (deduped case-insensitively).
 */
const SUPPLEMENTAL_SEO_KEYWORDS: readonly string[] = [
  "Exit Buttons(REX)",
  "Emergency Systems",
  "All Products",
  "MIfare/iCLASS",
  "UHF/ RFID",
  "Marketing Material, Access Control System",
  "Marketing Material, Batteries",
  "Marketing Material, Antennas",
  "Audio, Video and Loudmouth Stand-Alone PA Systems",
  "Cell Signal Boosters",
  "Close Racks",
  "Parts Accessories",
  "Auxiliary Lights",
  "Auxiliar Lights",
  "Hidden Strobes",
  "Traffic Director Bars",
  "Telescopic Lights",
  "Perimeter Lights",
  "Red-Blue-Green",
  "Indoor Bars",
  "Beacons",
  "Mini Bars",
  "Lightbars",
  "Sirens-Speakers-Controllers",
  "Off-Road Vehicles",
  "Accessories-Spare Parts",
  "Accesories for fixing cable",
  "Marketing Materia, Auxiliary Lights",
  "Rack/Cabinets Accesories",
  "Masts and Accesories",
  "Video Surveillance - Access Control",
  "Multiple Applications",
  "Grid - Tie Inverters",
  "Off - Grid Inverters",
  "SOLAR KIT Grid - Tie",
  "SOLAR KIT Off - Grid",
  "Energy Plants",
  "UPS/No-Breaks",
  "Wireless Routers, Cable",
  "Copper cabling",
  "Faceplates",
  "Jacks / Plugs",
  "Patch Cords",
  "Patch Panels",
  "Surface Mount Boxes",
  "Fiber Optic Cables",
  "Fiber Enclosures",
  "AC POWER",
  "Direct Current",
  "Electric tools",
  "Roof/ Wall Brackets",
  "IP Public Address Systems",
  "Audio/Video Conference",
  "Audio/Video IP Doorphones",
  "Gateways and ATAs",
  "IP Phones for Hotels",
  "5G / 4G (LTE) Routers",
  "Antennas, Cables and Accessories",
  "Splices Closures and Splitters",
  "Optic Fiber Transceivers",
  "POE Injectors",
  "Routers, Firewalls, Load Balancers",
  "Safety protecting cases",
  "Guyed Towers (Kits)",
  "Self-Support Towers",
  "Obstruction Lights",
  "Reusable Anchors",
  "Submersible Pumps",
  "Inverter Drives",
  "PWM Charge Controller",
  "MPPT Charge Controller",
  "Lightning Rod",
  "Grounding kits & lightning protection",
  "Battery Cabinets",
  "Battery Chargers",
  "Power Cables",
  "Emergency Lights",
  "Indoor LED Lighting",
  "Stand Alone",
  "Bolt",
  "Door Strikes",
  "Magnetic Door Lock",
  "Transformers",
  "Laminating Printers",
  "Ribbons",
  "Cable Grommets",
  "Cards and Tags",
  "Door Closers",
  "Relay Cards",
  "Wireless Controls",
  "USB Readers / Enrollers",
  "Emergency Door Bars",
  "Identification and Credentialing",
  "For Time and Attendance Control",
  "Flap Barriers",
  "Full Height Turnstiles",
  "Interphones",
  "Multi-apartments",
  "Accessories for Gate Operators",
  "Barrier Gates",
  "Gate Operators",
  "Replacement Parts",
  "Sliding Doors",
  "Monthly Specials",
  "Inventory Arrivals",
  "Clearance",
  "Marketing Material",
  "Specials and Marketing",
  "Digifort",
  "EPCOM Cloud",
  "Software VMS and Analytics",
  "Hard Disk Drives (HDD)",
  "NAS / SAN / eSATA Storage",
  "Portable Video Recorders",
  "Portatil Video Recorders",
  "Motorcycles",
  "Sirens",
  "Speakers",
  "Drivers",
  "Trackers GPS",
  "IoT, GPS and Telematics",
  "Backhaul Links",
  "PtP and PtMP Links",
  "900 MHz",
  "60, 70 and 80 GHz",
  "5 Ghz / 2.4 GHz Bands",
  "Omnidirectional",
  "Directional",
  "Sector",
  "Jumpers",
  "Volume Control",
  "Screen Mounting",
  "Outdoor Speakers",
  "Monitors, Screens and Videowall",
  "HDMI Products",
  "Audio Controllers",
  "Audio Cables",
  "Clamps and Fittings",
  "OLT / ONT / ONU",
  "Jumpers and Pigtails",
  "Fiber Optic Cable",
  "GPON",
  "Industrial",
  "Long Reach PoE",
  "Converters",
  "Networking",
  "Wall mount cabinets",
  "Outdoor cabinets",
  "Open Racks",
  "Rack Cabinets",
  "Multi-Purpose Enclosures",
  "Mounting Brackets",
  "Mounting Accessories",
  "Exterior / Interior Cabinets",
  "Redundant Power Supply (ATS)",
  "Metered",
  "Monitored",
  "Basic",
  "Switched",
  "PDU",
  "Voltage Converters",
  "Wall Adapters AC/DC",
  "Power Supplies With Backup",
  "PoE Switches",
  "PoE Injectors",
  "Long Reach PoE",
  "UPS - No Break",
  "Batteries",
  "Power Supplies",
  "Hemispheric / Fisheye",
  "Hidden Cameras",
  "Eyeball / Turret",
  "Cube",
  "Bullet",
  "4K",
  "IP Cameras",
  "NVRs Network Video Recorders",
  "Video Encoders and Decoders",
  "Mobile DVRs",
  "Mobile Video Recorders",
  "Video Recorders TurboHD (TVI)",
  "TurboHD Cameras (TVI) / AHD",
  "16-Channel TurboHD Kit",
  "4-Channel TurboHD Kit",
  "8-Channel TurboHD Kit",
  "Complete Systems (Kits)",
  "IP Megapixel",
  "Analog Door Phones",
  "Multi-Unit Apartment Intercom Systems",
  "Door Phones and Door Video Phones",
  "IP Doorphones",
  "TV Door Phone and Interphones",
  "VGA / DVI / HDMI",
  "Network Connectors",
  "Fiber optic",
  "Coaxial Jumpers",
  "Coaxial Cable and Connectors",
  "Cat6a",
  "Cat6",
  "Cat5e",
  "Category 5e",
  "Category 6",
  "Category 6A",
  "Category 7A",
  "Cable Raceways",
  "Cable Pathway",
  "Cable Ties",
  "PVC Pipeline / Boxes",
  "Cable Tray",
  "Cable Trays",
  "Mounting",
  "Union",
  "Connectors - Network Connectors",
  "Network Connectors",
  "Wi-Fi Networks",
  "Access Points",
  "Controllers",
  "Hotspots",
  "Signal Repeaters",
  "Wireless Adapters",
  "Voice Over IP - VoIP",
  "IP Phones",
  "Headsets",
  "IP Switches",
  "Surge Protection",
  "Ground Testers",
  "Video Testers",
  "Installation Accessories",
  "For UTP cable (Cat5e, Cat6)",
  "For RG59 Cable",
  "Electric Tools",
  "Solar Panels",
  "Solar Panel Mounts",
  "Solar PoE Converters",
  "Inverters/Charger",
  "Inverters",
  "DC to DC Converters",
  "Grid-Tie Inverters"
];

function normalizeKeywordKey(s: string): string {
  return s.trim().toLowerCase().replace(/\s+/g, " ");
}

/** All unique catalog + supplemental phrases for sitemap-adjacent SEO (visible lists + JSON-LD). */
export function getEshopIndexableKeywords(): string[] {
  const fromCatalog = ESHOP_DEPARTMENTS.flatMap((d) => [...d.lines]);
  const map = new Map<string, string>();
  for (const raw of [...fromCatalog, ...SUPPLEMENTAL_SEO_KEYWORDS]) {
    const t = raw.trim();
    if (t.length < 2) continue;
    const k = normalizeKeywordKey(t);
    if (!map.has(k)) map.set(k, t);
  }
  return [...map.values()].sort((a, b) => a.localeCompare(b, "en"));
}

/** Meta keywords tag: keep a bounded set (some crawlers still read `keywords`). */
export function getEshopKeywordsForMeta(): string[] {
  return getEshopIndexableKeywords().slice(0, 120);
}
